codecov:
  bot: 'codecov-bot'
  strict_yaml_branch: 'yaml-config'
  max_report_age: 24
  disable_default_path_fixes: no

coverage:
  range: 50..90 # coverage lower than 50 is red, higher than 90 green, between color code
  status:
    project:
      default:
        target: auto # auto % coverage target
        threshold: 100% # allow for 5% reduction of coverage without failing
    patch:
      default:
        target: auto # auto % coverage target
        threshold: 100% # allow for 5% reduction of coverage without failing

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false # if true: only post the comment if coverage changes
  require_base: no # [yes :: must have a base report to post]
  require_head: yes # [yes :: must have a head report to post]
